[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd frontend/vite-project && npm install"]

[phases.build]
cmds = ["cd frontend/vite-project && npm run build"]

[phases.start]
cmd = "cd frontend/vite-project && npm run preview -- --port $PORT"
